/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.KlijentController;
import domain.Gost;
import javax.swing.JOptionPane;
import modeli.TableModelGost;
import domain.Drzavljanstvo;

/**
 *
 * @author korisnk
 */
public class FormaPretraziGost extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaPretraziGost.class.getName());

    /**
     * Creates new form FormaPretraziGost
     */
    private TableModelGost model;
    public FormaPretraziGost(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Pretrazi gosta");
        initComponents();
        model = new TableModelGost();
        jTableGosti.setModel(model);
        jButtonpretraziGosta.addActionListener(e -> pretrazi());
        jButtonObrisiGosta.addActionListener(e -> obrisiSelektovanog());
        jButtonIzmeniGosta.addActionListener(e -> izmeniSelektovanog());

        popuniDrzavljanstva();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGosti = new javax.swing.JTable();
        jButtonpretraziGosta = new javax.swing.JButton();
        jButtonIzmeniGosta = new javax.swing.JButton();
        jButtonObrisiGosta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDrzavljanstvo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        jTextFieldIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImeActionPerformed(evt);
            }
        });

        jTableGosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableGosti);

        jButtonpretraziGosta.setText("PRETRAZI");
        jButtonpretraziGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpretraziGostaActionPerformed(evt);
            }
        });

        jButtonIzmeniGosta.setText("IZMENI GOSTA");
        jButtonIzmeniGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniGostaActionPerformed(evt);
            }
        });

        jButtonObrisiGosta.setText("OBRISI GOSTA");

        jLabel2.setText("PRETRAZI GOSTA");

        jTextFieldPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrezimeActionPerformed(evt);
            }
        });

        jLabel3.setText("Prezime:");

        jLabel4.setText("Drzavljanstvo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonIzmeniGosta)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonObrisiGosta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIme)
                                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jComboBoxDrzavljanstvo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(66, 66, 66)
                        .addComponent(jButtonpretraziGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonpretraziGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxDrzavljanstvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzmeniGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonObrisiGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImeActionPerformed

    private void jButtonpretraziGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpretraziGostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonpretraziGostaActionPerformed

    private void jButtonIzmeniGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniGostaActionPerformed
        int row = jTableGosti.getSelectedRow();
       /* if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Izaberi gosta iz tabele.");
            return;
        }*/

        modeli.TableModelGost tm = (modeli.TableModelGost) jTableGosti.getModel();
        domain.Gost selektovan = tm.getGostAt(row);  

        FormaNoviGost dlg = new FormaNoviGost((java.awt.Frame) getParent(), true, selektovan);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_jButtonIzmeniGostaActionPerformed

    private void jTextFieldPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrezimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormaPretraziGost dialog = new FormaPretraziGost(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeniGosta;
    private javax.swing.JButton jButtonObrisiGosta;
    private javax.swing.JButton jButtonpretraziGosta;
    private javax.swing.JComboBox<Drzavljanstvo> jComboBoxDrzavljanstvo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGosti;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    private void pretrazi() {
            try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            domain.Drzavljanstvo drz = (domain.Drzavljanstvo) jComboBoxDrzavljanstvo.getSelectedItem();

            Gost gost = new Gost();
            if (!ime.isEmpty()) gost.setIme(ime);
            if (!prezime.isEmpty()) gost.setPrezime(prezime);
            if (drz != null) gost.setDrzavljanstvo(drz);

            java.util.ArrayList<Gost> lista = controller.KlijentController.getInstance().searchGost(gost);
            model.setData(lista);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Greska pri pretrazi: " + ex.getMessage());
        }
    }

    private void obrisiSelektovanog() {
        int row = jTableGosti.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Izaberi gosta za brisanje."); return; }

        Gost g = model.getGostAt(row);
        int potv = JOptionPane.showConfirmDialog(this,"Obrisati gosta " + g + "?", "Potvrda", JOptionPane.YES_NO_OPTION);
        if (potv != JOptionPane.YES_OPTION) return;

        try {
            KlijentController.getInstance().deleteGost(g); 
            model.removeRow(row);                          
            JOptionPane.showMessageDialog(this, "Gost obrisan.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri brisanju: " + ex.getMessage());
        }
    }

    private void izmeniSelektovanog() {
        int row = jTableGosti.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Izaberi gosta iz tabele.");
            return;
        }

        Gost selektovan = model.getGostAt(row);
        if (selektovan == null) {
            JOptionPane.showMessageDialog(this, "Nije moguce procitati selektovanog gosta.");
            return;
        }

        FormaNoviGost dlg = new FormaNoviGost((java.awt.Frame) getParent(), true, selektovan);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);  

        pretrazi(); 
    }

    private void popuniDrzavljanstva() {
         try {
            java.util.ArrayList<domain.Drzavljanstvo> lista =
            controller.KlijentController.getInstance().getAllDrzavljanstvo();
            jComboBoxDrzavljanstvo.removeAllItems();
            jComboBoxDrzavljanstvo.addItem(null); 
            for (domain.Drzavljanstvo d : lista) jComboBoxDrzavljanstvo.addItem(d);
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,"Greska pri ucitavanju drzavljanstava: " + ex.getMessage());
    }
    }
}
