/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.KlijentController;
import domain.Drzavljanstvo;
import domain.Gost;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author korisnk
 */
public class FormaNoviGost extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaNoviGost.class.getName());

    /**
     * Creates new form FormaNoviGost
     */
    public FormaNoviGost(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Unos novog gosta");
        setLocationRelativeTo(parent);
        jButtonIzmeniGosta.setVisible(false);
       // jButtonZatvori.addActionListener(e -> dispose());
       jButtonDodajGosta.addActionListener(e -> sacuvajGosta());
        jButtonObrisiGosta.setVisible(false);
        jButtonObrisiGosta.setEnabled(false);
        popuniDrzavljanstva();
       }

    
    int hiddenIdGost = 0;

public FormaNoviGost(java.awt.Frame parent, boolean modal, domain.Gost selektovan) {
    super(parent, modal);       
    initComponents();
    setTitle("Detalji gosta");
    setLocationRelativeTo(parent);

    jButtonDodajGosta.setVisible(false);
    jButtonDodajGosta.setEnabled(false);
    jButtonIzmeniGosta.setVisible(true);
    jButtonIzmeniGosta.setEnabled(true);

    jButtonObrisiGosta.setVisible(true);
    jButtonObrisiGosta.setEnabled(true);
    
    popuniDrzavljanstva();
    if(selektovan!=null){
    hiddenIdGost = selektovan.getIdGost();
    jTextFieldIme.setText(selektovan.getIme());
    jTextFieldPrezime.setText(selektovan.getPrezime());
    jTextFieldEmail.setText(selektovan.getEmail());
    }
    if(selektovan==null) return;
    int idDrz = (selektovan.getDrzavljanstvo() != null) ? selektovan.getDrzavljanstvo().getIdDrzavljanstvo() : -1;
    for (int i = 0; i < jComboBoxDrzavljanstvo.getItemCount(); i++) {
        Drzavljanstvo d = jComboBoxDrzavljanstvo.getItemAt(i);
        if (d != null && d.getIdDrzavljanstvo() == idDrz) {
            jComboBoxDrzavljanstvo.setSelectedIndex(i);
            break;
            }
    
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonZatvori = new javax.swing.JButton();
        jButtonDodajGosta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxDrzavljanstvo = new javax.swing.JComboBox<>();
        jButtonIzmeniGosta = new javax.swing.JButton();
        jButtonObrisiGosta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ime:");

        jLabel2.setText("prezime:");

        jLabel3.setText("email:");

        jButtonZatvori.setText("ZATVORI");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        jButtonDodajGosta.setText("DODAJ GOSTA");

        jLabel5.setText("drzavljanstvo:");

        jButtonIzmeniGosta.setText("IZMENI GOSTA");
        jButtonIzmeniGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniGostaActionPerformed(evt);
            }
        });

        jButtonObrisiGosta.setText("OBRISI GOSTA");
        jButtonObrisiGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiGostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jComboBoxDrzavljanstvo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDodajGosta)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonObrisiGosta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIzmeniGosta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxDrzavljanstvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonObrisiGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodajGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIzmeniGosta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    private void jButtonIzmeniGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniGostaActionPerformed
            try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            String email = jTextFieldEmail.getText().trim();
            domain.Drzavljanstvo drz = (domain.Drzavljanstvo) jComboBoxDrzavljanstvo.getSelectedItem();

            if (ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || drz == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sva polja su obavezna.");
                return;
            }
            if (!email.contains("@")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Neispravan e-mail.");
                return;
            }
            
            domain.Gost izmenjen = new domain.Gost(hiddenIdGost, ime, prezime, email, drz);
            controller.KlijentController.getInstance().updateGost(izmenjen);

            javax.swing.JOptionPane.showMessageDialog(this, "Gost je uspesno izmenjen.");
            this.dispose();  
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni gosta.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIzmeniGostaActionPerformed

    private void jButtonObrisiGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiGostaActionPerformed
        
       if (hiddenIdGost <= 0) {
        JOptionPane.showMessageDialog(this, "Nema vazeceg ID-ja gosta za brisanje.");
        return;
    }

    int potvrda = JOptionPane.showConfirmDialog(
            this,
            "Obrisati ovog gosta?",
            "Potvrda",
            JOptionPane.YES_NO_OPTION
    );
    if (potvrda != JOptionPane.YES_OPTION) return;

    try {
        Gost g = new Gost();
        g.setIdGost(hiddenIdGost);    
        KlijentController.getInstance().deleteGost(g);
        JOptionPane.showMessageDialog(this, "Gost je uspesno obrisan.");
        dispose();                      // zatvori dijalog
    } catch (java.sql.SQLIntegrityConstraintViolationException ex) {
        JOptionPane.showMessageDialog(
            this,
            "Gost ne moze da se obrise jer postoje povezani racuni.",
            "Greska",
            JOptionPane.ERROR_MESSAGE
        );
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(
            this,
            "Sistem ne moze da obrise gosta.",
            "Greska",
            JOptionPane.ERROR_MESSAGE
        );
    }



    }//GEN-LAST:event_jButtonObrisiGostaActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajGosta;
    private javax.swing.JButton jButtonIzmeniGosta;
    private javax.swing.JButton jButtonObrisiGosta;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JComboBox<Drzavljanstvo> jComboBoxDrzavljanstvo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    private void sacuvajGosta() {
        try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            String email = jTextFieldEmail.getText().trim();
            domain.Drzavljanstvo drz = (domain.Drzavljanstvo) jComboBoxDrzavljanstvo.getSelectedItem();

            if (ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || drz == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Sva polja su obavezna.");
                return;
            }
            if (!email.contains("@")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Neispravan e-mail.");
                return;
            }

            domain.Gost g = new domain.Gost(0, ime, prezime, email, drz);
            KlijentController.getInstance().addGost(g);

            javax.swing.JOptionPane.showMessageDialog(this, "Gost je uspesno dodat.");
            dispose();
        
    } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Sistem ne moze da doda gosta.","Greska", JOptionPane.ERROR_MESSAGE);
    }
    }

    private void popuniDrzavljanstva() {
         try {
             ArrayList<domain.Drzavljanstvo> lista =
                   KlijentController.getInstance().getAllDrzavljanstvo();
            jComboBoxDrzavljanstvo.removeAllItems();
            for (domain.Drzavljanstvo d : lista) {
                jComboBoxDrzavljanstvo.addItem(d);
            }
    } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Greska pri ucitavanju drzavljanstava: " + ex.getMessage());
    }
    }
}
